name: CI - Retrain Model

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
      - name: Install dependencies
        run: pip install mlflow==2.19.0 scikit-learn pandas numpy
      - name: Run MLflow Project (retraining)
        working-directory: MLProject
        run: mlflow run . --env-manager=local
